### ISSUE TITLE
Waypoint Updater suffers "bad callback" errors

### ISSUE THREAD

**Issue by xperroni** [whats-in-a-name/CarND-Capstone#7]
When running the Waypoint Updater node, the following errors are printed to the console in rapid succession:

    [ERROR] [1504552404.490212]: bad callback: <bound method WaypointUpdater.pose_cb of <__main__.WaypointUpdater object at 0x7faa44a35e90>>
    Traceback (most recent call last):
    File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
        cb(msg)
    File "/home/erios/Udacity/Courses/SDCND/Projects/CarND-Capstone/ros/src/waypoint_updater/waypoint_updater.py", line 49, in pose_cb
        nearest_wp = self.find_nearest_wp(msg.pose.position.x, msg.pose.position.y, self.map_wp)
    AttributeError: 'WaypointUpdater' object has no attribute 'map_wp'

    [ERROR] [1504552406.344000]: bad callback: <bound method WaypointUpdater.pose_cb of <__main__.WaypointUpdater object at 0x7faa44a35e90>>
    Traceback (most recent call last):
    File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
        cb(msg)
    File "/home/erios/Udacity/Courses/SDCND/Projects/CarND-Capstone/ros/src/waypoint_updater/waypoint_updater.py", line 49, in pose_cb
        nearest_wp = self.find_nearest_wp(msg.pose.position.x, msg.pose.position.y, self.map_wp)
    File "/home/erios/Udacity/Courses/SDCND/Projects/CarND-Capstone/ros/src/waypoint_updater/waypoint_updater.py", line 91, in find_nearest_wp
        val_min = distance_sqr(x, y, map_xyz[0].pose.pose.position.x, map_xyz[0].pose.pose.position.y)
    NameError: global name 'distance_sqr' is not defined

**Comment by xperroni** [comment]
Fixed, see commit 03e830faa3f505d4b6f62242fe160685414928ec for details.
